FROM docker.io/python:3.12.9

LABEL version 0.0.3-dev

WORKDIR /usr/src/app

RUN pip install --no-cache-dir \
    fastapi[standard] \
    pydantic \
    pyjwt \
    passlib[bcrypt]

EXPOSE 8000

CMD [ "uvicorn", "main:app", "--reload", "--workers", "1", "--host", "0.0.0.0", "--port", "8000" ]
