services:
  webapp: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fast-api-webapp
    restart: always
    volumes:
      - ./requirements.txt:/usr/src/requirements.txt
      - ./src:/usr/src/app
    ports:
      - 9000:8000